vich_uploader:
    db_driver: orm
    mappings:
        cours_pdf:
            uri_prefix: /uploads/cours
            upload_destination: '%kernel.project_dir%/public/uploads/cours'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer